/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.event.*;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author turupawn
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        pb_vida1 = new javax.swing.JProgressBar();
        pb_vida3 = new javax.swing.JProgressBar();
        jLabel_personaje3 = new javax.swing.JLabel();
        jLabel_personaje1 = new javax.swing.JLabel();
        jLabel_personaje2 = new javax.swing.JLabel();
        jLabel_personaje4 = new javax.swing.JLabel();
        pb_vida2 = new javax.swing.JProgressBar();
        pb_vida4 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personaje1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pb_vida1.setValue(100);
        getContentPane().add(pb_vida1);
        pb_vida1.setBounds(26, 50, 193, 33);

        pb_vida3.setValue(100);
        getContentPane().add(pb_vida3);
        pb_vida3.setBounds(682, 50, 193, 33);

        jLabel_personaje3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personaje2.png"))); // NOI18N
        getContentPane().add(jLabel_personaje3);
        jLabel_personaje3.setBounds(648, 89, 250, 330);

        jLabel_personaje1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personaje1.png"))); // NOI18N
        getContentPane().add(jLabel_personaje1);
        jLabel_personaje1.setBounds(10, 89, 250, 288);

        jLabel_personaje2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personaje3.png"))); // NOI18N
        getContentPane().add(jLabel_personaje2);
        jLabel_personaje2.setBounds(266, 89, 250, 310);

        jLabel_personaje4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personaje4.png"))); // NOI18N
        getContentPane().add(jLabel_personaje4);
        jLabel_personaje4.setBounds(904, 89, 250, 320);

        pb_vida2.setValue(100);
        getContentPane().add(pb_vida2);
        pb_vida2.setBounds(257, 50, 193, 33);

        pb_vida4.setValue(100);
        getContentPane().add(pb_vida4);
        pb_vida4.setBounds(930, 50, 193, 33);

        jButton4.setText("Super ataque");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(550, 300, 110, 23);

        jButton1.setText("Atacar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 200, 65, 23);

        jButton3.setText("Curarse");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 250, 80, 23);

        jButton2.setText("Equipo 1");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 10, 110, 23);

        jButton5.setText("Equipo 2");
        getContentPane().add(jButton5);
        jButton5.setBounds(850, 10, 110, 23);

        jButton6.setText("Juego en curso");
        getContentPane().add(jButton6);
        jButton6.setBounds(510, 380, 190, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-110, -400, 1400, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        double random = Math.random()*15;
        double personaje_atacado = Math.random()*2;
        int nueva_vida3=pb_vida3.getValue(),nueva_vida4=pb_vida3.getValue();
        
        if(jButton4.isEnabled())
        {
            if(personaje_atacado>=1){
                jButton4.setEnabled(false);
                nueva_vida3 = pb_vida3.getValue()/10;
                pb_vida3.setValue(nueva_vida3);
            }else{
                jButton4.setEnabled(false);
                nueva_vida4 = pb_vida4.getValue()/10;
                pb_vida4.setValue(nueva_vida4);
            }
            
            if(nueva_vida3<=0 && nueva_vida4<=0)
            {
                jButton6.setText("Ha ganado el equipo1!!");
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
            }

            Timer timer = new Timer(1000, new AbstractAction(){
                @Override
                public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                int nueva_vida1=pb_vida1.getValue(),nueva_vida2=pb_vida2.getValue();
                
                if(ataque_random<40)
                {
                    if(personaje_atacado>=1 && nueva_vida1>0){
                        System.out.println("Ataque normal al personaje1");
                        double random = Math.random()*15;
                        nueva_vida1 = pb_vida1.getValue()-(int)random;
                        pb_vida1.setValue(nueva_vida1);
                    }else{
                        System.out.println("Ataque normal al personaje2");
                        double random = Math.random()*15;
                        nueva_vida2 = pb_vida2.getValue()-(int)random;
                        pb_vida2.setValue(nueva_vida2);
                    }
                    if(nueva_vida1<=0 && nueva_vida2<=0)
                    {
                        jButton6.setText("Ha ganado el equipo2!!");
                        jButton1.setEnabled(false);
                        jButton3.setEnabled(false);
                    }
                }else if(ataque_random<90){
                    if(personaje_atacado<=1){
                        System.out.println("Super ataque al personaje1");
                        pb_vida1.setValue(1);
                    }else{
                        System.out.println("Super ataque al personaje2");
                        pb_vida2.setValue(1);
                    }
                    if(nueva_vida1<=0 && nueva_vida2<=0)
                    {
                        jButton6.setText("Ha ganado el equipo2!!");
                        jButton1.setEnabled(false);
                        jButton3.setEnabled(false);
                    }
                }else{
                    if(personaje_atacado<=1){
                        System.out.println("Super curar al personaje1");
                        pb_vida1.setValue(100);
                    }else{
                        System.out.println("Super curar al personaje2");
                        pb_vida2.setValue(100);
                    }
                    if(nueva_vida1<=0 && nueva_vida2<=0)
                    {
                        jButton6.setText("Ha ganado el equipo2!!");
                        jButton1.setEnabled(false);
                        jButton3.setEnabled(false);
                    }
                }
            }
            });
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        double random = Math.random()*15;
        double personaje_atacado = Math.random()*2;
        int nueva_vida3=pb_vida3.getValue(),nueva_vida4=pb_vida3.getValue();
        if(nueva_vida3>0 || nueva_vida4>0 ){
            if(personaje_atacado>=1){
                nueva_vida3 = pb_vida3.getValue()-(int)random;
                pb_vida3.setValue(nueva_vida3);
            }else{
                nueva_vida4 = pb_vida4.getValue()-(int)random;
                pb_vida4.setValue(nueva_vida4);
            }
            if(nueva_vida3<=0 && nueva_vida4<=0)
            {
                jButton6.setText("Ha ganado el equipo1!!");
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
            }

            Timer timer = new Timer(1000, new AbstractAction(){
                @Override
                public void actionPerformed(ActionEvent ae){
                    double ataque_random = Math.random()*100;
                    int nueva_vida1=pb_vida1.getValue(),nueva_vida2=pb_vida2.getValue();
                    if(nueva_vida1>0 || nueva_vida2>0 ){
                        if(ataque_random<40)
                        {
                            if(personaje_atacado>=1 && nueva_vida1>0){
                                System.out.println("Ataque normal al personaje1");
                                double random = Math.random()*15;
                                nueva_vida1 = pb_vida1.getValue()-(int)random;
                                pb_vida1.setValue(nueva_vida1);
                            }else{
                                System.out.println("Ataque normal al personaje2");
                                double random = Math.random()*15;
                                nueva_vida2 = pb_vida2.getValue()-(int)random;
                                pb_vida2.setValue(nueva_vida2);
                            }
                            if(nueva_vida1<=0 && nueva_vida2<=0)
                            {
                                jButton6.setText("Ha ganado el equipo2!!");
                                jButton1.setEnabled(false);
                                jButton3.setEnabled(false);
                            }
                        }else if(ataque_random<90){
                            if(personaje_atacado<=1){
                                System.out.println("Super ataque al personaje1");
                                pb_vida1.setValue(1);
                            }else{
                                System.out.println("Super ataque al personaje2");
                                pb_vida2.setValue(1);
                            }
                            if(nueva_vida1<=0 && nueva_vida2<=0)
                            {
                                jButton6.setText("Ha ganado el equipo2!!");
                                jButton1.setEnabled(false);
                                jButton3.setEnabled(false);
                            }
                        }else{
                            if(personaje_atacado<=1){
                                System.out.println("Super cuarar al personaje1");
                                pb_vida1.setValue(100);
                            }else{
                                System.out.println("Super curar al personaje2");
                                pb_vida2.setValue(100);
                            }
                            if(nueva_vida1<=0 && nueva_vida2<=0)
                            {
                                jButton6.setText("Ha ganado el equipo2!!");
                                jButton1.setEnabled(false);
                                jButton3.setEnabled(false);
                            }
                        }
                    }
                }
            });
            timer.setRepeats(false);
            timer.start();
        }
    }                                     

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {                                     
       
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        double personaje_atacado = Math.random()*2;
        int nueva_vida1=pb_vida1.getValue(),nueva_vida2=pb_vida2.getValue();
        
        if(personaje_atacado>=1 && nueva_vida1>0){
            System.out.println("Curar al personaje1");
            double random = Math.random()*100;
            nueva_vida1 = pb_vida1.getValue()+(int)random;
            pb_vida1.setValue(nueva_vida1);
        }else{
            System.out.println("Curar al personaje2");
            double random = Math.random()*100;
            nueva_vida2 = pb_vida2.getValue()+(int)random;
            pb_vida2.setValue(nueva_vida2);
        }
        if(nueva_vida1<=0 && nueva_vida2<=0)
        {
            jButton6.setText("Ha ganado el equipo 2");
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                int nueva_vida1=pb_vida1.getValue(),nueva_vida2=pb_vida2.getValue();
                
                if(ataque_random<40)
                {
                    if(personaje_atacado>=1 && nueva_vida1>0){
                        System.out.println("Ataque normal al personaje1");
                        double random = Math.random()*15;
                        nueva_vida1 = pb_vida1.getValue()-(int)random;
                        pb_vida1.setValue(nueva_vida1);
                    }else{
                        System.out.println("Ataque normal al personaje2");
                        double random = Math.random()*15;
                        nueva_vida2 = pb_vida2.getValue()-(int)random;
                        pb_vida2.setValue(nueva_vida2);
                    }
                    if(nueva_vida1<=0 && nueva_vida2<=0)
                    {
                        jButton6.setText("Ha ganado el equipo2");
                        jButton1.setEnabled(false);
                        jButton3.setEnabled(false);
                    }
                }else if(ataque_random<90){
                    if(personaje_atacado<=1){
                        System.out.println("Super ataque al personaje1");
                        pb_vida1.setValue(1);
                    }else{
                        System.out.println("Super ataque al personaje2");
                        pb_vida2.setValue(1);
                    }
                    if(nueva_vida1<=0 && nueva_vida2<=0)
                    {
                        jButton6.setText("Ha ganado el equipo 2");
                        jButton1.setEnabled(false);
                        jButton3.setEnabled(false);
                    }
                }else{
                    if(personaje_atacado<=1){
                        System.out.println("Super cuarar al personaje1");
                        pb_vida1.setValue(100);
                    }else{
                        System.out.println("Super curar al personaje2");
                        pb_vida2.setValue(100);
                    }
                    if(nueva_vida1<=0 && nueva_vida2<=0)
                    {
                        jButton6.setText("Ha ganado el equipo 2");
                        jButton1.setEnabled(false);
                        jButton3.setEnabled(false);
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
       
    }//GEN-LAST:event_jButton3MousePressed
                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        File background= new File("Pokemon BlueRed Soundtrack   Opening.wav");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
                PlaySound(background);
     
            }
        });
    }
    public static void PlaySound(File Sound ){
        try{
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(Sound));
            clip.start();
        }catch(Exception e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_personaje1;
    private javax.swing.JLabel jLabel_personaje2;
    private javax.swing.JLabel jLabel_personaje3;
    private javax.swing.JLabel jLabel_personaje4;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    private javax.swing.JProgressBar pb_vida3;
    private javax.swing.JProgressBar pb_vida4;
    // End of variables declaration//GEN-END:variables
}
